# API server ajoute/normalise des champs (ex. preserveUnknownFields: false, etc.). Argo CD voit ces champs “en plus” → diff perpétuel → OutOfSync
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argo-rollouts
spec:
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jqPathExpressions:
        - .spec.preserveUnknownFields
        - .spec.versions[]?.schema?.openAPIV3Schema?.["x-kubernetes-preserve-unknown-fields"]
        - .spec.versions[]?.schema?.openAPIV3Schema?.properties?.spec?.["x-kubernetes-preserve-unknown-fields"]
        - .spec.versions[]?.schema?.openAPIV3Schema?.properties?.status?.["x-kubernetes-preserve-unknown-fields"]
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true