apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
spec:
  template:
    spec:
      containers:
        - name: app
          image: argoproj/rollouts-demo:yellow   # tag par défaut en staging
