apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-apps
  namespace: argocd
spec:
  destinations:
    - namespace: 'myapp-*'
      server: https://kubernetes.default.svc
  sourceRepos:
    - '*'
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace                 # optionnel, si apps créent leurs ns