apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Le namespace de nos objets namespaced (SA, RBAC, Deploy, Services…)
namespace: argo-rollouts

resources:
  # 1) Namespace (géré en GitOps)
  - namespace.yaml

  # 2) Manifeste officiel (pinné sur une version précise)
  #    Contient le controller + RBAC + Services + Webhooks + CRDs.
  - https://github.com/argoproj/argo-rollouts/releases/download/v1.8.3/install.yaml

patches:
  - path: patches/argo-rollouts-ignore-crd-diff-patch.yaml
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: argo-rollouts