apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ingcloud-fr/app-rollouts-demo
    targetRevision: main
    path: argo-rollouts-controler
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-rollouts
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jqPathExpressions:
        - .spec.preserveUnknownFields
        - .spec.versions[]?.schema?.openAPIV3Schema?.["x-kubernetes-preserve-unknown-fields"]
        - .spec.versions[]?.schema?.openAPIV3Schema?.properties?.spec?.["x-kubernetes-preserve-unknown-fields"]
        - .spec.versions[]?.schema?.openAPIV3Schema?.properties?.status?.["x-kubernetes-preserve-unknown-fields"]
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
      #- Replace=true       