apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  source:
    repoURL: REPO_URL
    targetRevision: main
    path: argo-rollouts
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-rollouts
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true          # au cas où, mais on a aussi namespace.yaml
      #- ServerSideApply=true          # (recommandé) pour les CRDs
