apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "30"
  finalizers:
    - resources-finalizer.argocd.argoproj.io    
spec:
  project: default
  source:
    repoURL: https://github.com/ingcloud-fr/app-rollouts-demo
    targetRevision: main
    path: myapp/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    #namespace: myapp-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true   
