apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-canary-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "30"
  finalizers:
    - resources-finalizer.argocd.argoproj.io    
spec:
  project: default # project-apps #default
  source:
    repoURL: https://github.com/ingcloud-fr/app-rollouts-demo
    targetRevision: main
    path: myapps/myapp-canary/overlays/prod
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
