# kubectl apply -f apps/root.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-apps
  namespace: argocd
  # delete en cascade
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  project: default
  source:
    repoURL: https://github.com/ingcloud-fr/app-rollouts-demo
    targetRevision: main
    path: apps/children
    directory:
      recurse: true           # lit tous les manifests du répertoire
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
